language: ruby
rvm:
  - 2.2
before_script:
  - gem install awesome_bot
script:
  - awesome_bot README.md --allow-dupe
  - awesome_bot Libraries/Features.md --allow-dupe
  - awesome_bot Libraries/File-Size.md --allow-dupe
notifications:
  email: false
